In [27]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

In [29]:
# Initialize the network parameters
np.random.seed(42)
input_size = 3  # Example input features
hidden1_size = 7  # First hidden layer (7 neurons)
hidden2_size = 5  # Second hidden layer (5 neurons)
output_size = 2  # Two output units

# Random weight initialization
w1 = np.random.randn(input_size, hidden1_size)
b1 = np.random.randn(hidden1_size)
w2 = np.random.randn(hidden1_size, hidden2_size)
b2 = np.random.randn(hidden2_size)
w3 = np.random.randn(hidden2_size, output_size)
b3 = np.random.randn(output_size)

In [31]:
x_train = np.array([[0.5, 0.3, 0.8]])  # Input
y_train = np.array([[1, 0]])  # Target output

learning_rate = 0.01
num_epochs = 2

In [33]:
for epoch in range(num_epochs):
    for x, y in zip(x_train, y_train):
        # Forward propagation
        z1 = np.dot(x, w1) + b1
        a1 = sigmoid(z1)
        
        z2 = np.dot(a1, w2) + b2
        a2 = sigmoid(z2)
        
        z3 = np.dot(a2, w3) + b3
        a3 = sigmoid(z3)
        
        # Compute squared error
        error = 0.5 * np.sum((y - a3) ** 2)
        
        # Backpropagation
        d3 = (a3 - y) * sigmoid_derivative(a3)
        dw3 = np.dot(a2.reshape(-1, 1), d3.reshape(1, -1))
        db3 = d3
        
        d2 = np.dot(w3, d3) * sigmoid_derivative(a2)
        dw2 = np.dot(a1.reshape(-1, 1), d2.reshape(1, -1))
        db2 = d2
        
        d1 = np.dot(w2, d2) * sigmoid_derivative(a1)
        dw1 = np.dot(x.reshape(-1, 1), d1.reshape(1, -1))
        db1 = d1
        
        # Update weights and biases
        w3 -= learning_rate * dw3
        b3 -= learning_rate * db3
        
        w2 -= learning_rate * dw2
        b2 -= learning_rate * db2
        
        w1 -= learning_rate * dw1
        b1 -= learning_rate * db1
        
        print(f"Epoch {epoch+1}, Error: {error:.4f}")


Epoch 1, Error: 0.3702
Epoch 2, Error: 0.3689


In [37]:
print("Final Weights and Biases:")
print("w1:", w1)
print("b1:", b1)
print("w2:", w2)
print("b2:", b2)
print("w3:", w3)
print("b3:", b3)

Final Weights and Biases:
w1: [[ 0.49634931 -0.13834337  0.64757488  1.52338987 -0.23397542 -0.23411297
   1.57922215]
 [ 0.76721582 -0.46952183  0.54249185 -0.46320168 -0.46562298  0.24197666
  -1.91327465]
 [-1.72550158 -0.56241404 -1.01301297  0.31482335 -0.90773935 -1.41226533
   1.4656637 ]]
b1: [-0.22650598  0.06737007 -1.4249755  -0.5436627   0.11127849 -1.15094561
  0.37571668]
w2: [[-0.60054949 -0.29185205 -0.60195236  1.85168122 -0.01343616]
 [-1.05758109  0.82231448 -1.22120138  0.20799461 -1.95958124]
 [-1.328132    0.19676531  0.73831767  0.17100654 -0.11561128]
 [-0.30089158 -1.47889842 -0.7204286  -0.46205837  1.05726743]
 [ 0.34372579 -1.76323093  0.3237878  -0.38580172 -0.67684841]
 [ 0.61170876  1.0309419   0.93119066 -0.83943483 -0.30919015]
 [ 0.33157471  0.97499271 -0.48003184 -0.18774225 -1.10612189]]
b2: [-1.19584199  0.81187873  1.35523545 -0.07445044  1.00378251]
w3: [[ 0.36210972 -0.6455275 ]
 [ 0.36330398  1.5363939 ]
 [-0.03418062  1.56322733]
 [-2.61837078 